using System;
using System.Collections.Generic;

namespace GymManagementSystem.Localization
{
    internal static class MainPanelSpanishStrings
    {
        internal static readonly IReadOnlyDictionary<string, string> EnglishToSpanish =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Dashboard", "Panel principal" },
                { "Members", "Miembros" },
                { "Employees", "Empleados" },
                { "Trainers", "Entrenadores" },
                { "Revenue", "Ingresos" },
                { "Member's Attendance", "Asistencia de miembros" },
                { "Membership Plan", "Plan de membresía" },
                { "Membership Plans", "Planes de membresía" },
                { "Admin Panel", "Panel de administración" },
                { "Admin Page", "Página de administración" },
                { "Log Out", "Cerrar sesión" },
                { "Register a Member", "Registrar un miembro" },
                { "Edit a Member", "Editar un miembro" },
                { "Delete Member", "Eliminar miembro" },
                { "Search", "Buscar" },
                { "Member List", "Lista de miembros" },
                { "Register Member", "Registrar miembro" },
                { "Register Trainer", "Registrar entrenador" },
                { "Edit Trainer", "Editar entrenador" },
                { "Delete Trainer", "Eliminar entrenador" },
                { "View PT Session", "Ver sesión PT" },
                { "Register Plan", "Registrar plan" },
                { "Delete Plan", "Eliminar plan" },
                { "Edit Plan", "Editar plan" },
                { "PT Sessions", "Sesiones PT" },
                { "Create Session", "Crear sesión" },
                { "Edit Session", "Editar sesión" },
                { "Cancel Session", "Cancelar sesión" },
                { "Register Staff", "Registrar personal" },
                { "Edit Staff Info", "Editar personal" },
                { "Delete Staff", "Eliminar personal" },
                { "Total Members", "Total de miembros" },
                { "Total Employees", "Total de empleados" },
                { "Revenue This Month", "Ingresos del mes" },
                { "Active Subscription", "Suscripción activa" },
                { "Recent Members", "Miembros recientes" },
                { "Audit Log", "Registro de auditoría" },
                { "member_id", "Ref." },
                { "First Name", "Nombre" },
                { "Last Name", "Apellido" },
                { "Email", "Correo" },
                { "Phone", "Teléfono" },
                { "Joined Date", "Fecha de alta" },
                { "Join Date", "Fecha de alta" },
                { "Status", "Estado" },
                { "ID", "ID" },
                {"Check In", "Llegada" },
                {"Check Out", "Salida" },
                {"From:","Desde"},
                {"To:", "Hasta"},
                {"Method:", "Método"},
                {"Filter", "Filtrar"},
                {"Reset", "Restablecer"},
                {"Total Revenue", "Ingresos totales"},
                {"Total Payments", "Pagos totales"},
                {"Average Payment", "Pago promedio"},
                {"Monthly Revenue", "Ingresos mensuales"},
                {"Series 1", "Serie 1"},
                {"Member Check In/Out", "Entrada/Salida de miembros"},
                {"Search Member:", "Buscar miembro:"},
               
                {"Currently in Gym:", "Actualmente en el gimnasio:"},
                {"Today's Attendance Log:", "Registro de asistencia de hoy:"},
                {"Position", "Posición"},
                {"Role", "Rol"},
                {"Salary", "Salario"},
                {"Specialization", "Especialización"},
                {"Hourly Rate", "Tarifa por hora"},
                {"Payment ID", "ID de pago"},
                {"Member Name", "Nombre del miembro"},
                {"Amount", "Amount"},
                {"Plan Name", "Nombre del plan"},
                {"Payment Date", "Fecha de pago"},
                {"Emergency Contact Name", "Nombre del contacto de emergencia"},
                {"Currentlry in Gym", "Actualmente en el gimnasio"},
                {"Plan ID", "ID del plan"},
{"Name", "Nombre"},
{"Duration Name", "Duración"},
{"price", "precio"},
{"description", "descripción"},
                {"Emergency Contact Phone", "Teléfono del contacto de emergencia"},

            };
    }
}
