using System;
using System.Collections.Generic;

namespace GymManagementSystem.Localization
{
    internal static class MainPanelFrenchStrings
    {
        internal static readonly IReadOnlyDictionary<string, string> EnglishToFrench =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Dashboard", "Tableau de bord" },
                { "Members", "Membres" },
                { "Employees", "Employés" },
                { "Trainers", "Entraîneurs" },
                { "Revenue", "Revenu" },
                { "Member's Attendance", "Présence des membres" },
                { "Membership Plan", "Abonnements" },
                { "Membership Plans", "Abonnements" },
                { "Admin Panel", "Panneau admin" },
                { "Admin Page", "Page d'administration" },
                { "Log Out", "Déconnexion" },
                { "Register a Member", "Inscrire un membre" },
                { "Edit a Member", "Modifier un membre" },
                { "Delete Member", "Supprimer membre" },
                { "Search", "Rechercher" },
                { "Member List", "Liste des membres" },
                { "Register Member", "Inscrire membre" },
                { "Register Trainer", "Inscrire entraîneur" },
                { "Edit Trainer", "Modifier entraîneur" },
                { "Delete Trainer", "Supprimer entraîneur" },
                { "View PT Session", "Voir session PT" },
                { "Register Plan", "Inscrire plan" },
                { "Delete Plan", "Supprimer plan" },
                { "Edit Plan", "Modifier plan" },
                { "PT Sessions", "Sessions PT" },
                { "Create Session", "Créer session" },
                { "Edit Session", "Modifier session" },
                { "Cancel Session", "Annuler session" },
                { "Register Staff", "Ajouter personnel" },
                { "Edit Staff Info", "Modifier personnel" },
                { "Delete Staff", "Supprimer personnel" },
                { "Total Members", "Total des membres" },
                { "Total Employees", "Total des employés" },
                { "Revenue This Month", "Revenu du mois" },
                { "Active Subscription", "Abonnement actif" },
                { "Recent Members", "Membres récents" },
                { "Audit Log", "Journal d'audit" },
                { "member_id", "Réf." },
                { "First Name", "Prénom" },
                { "Last Name", "Nom" },
                { "Email", "Courriel" },
                { "Phone", "Téléphone" },
                { "Joined Date", "Date d'inscription" },
                { "Join Date", "Date d'inscription" },
                { "Status", "Statut" },
                { "ID", "ID" },
                {"Check In", "Arrivé" },
                {"Check Out", "Départ" },
                {"From:","De"},
                {"To:", "À"},
                {"Method:", "Méthode"},
                {"Filter", "Filtrer"},
                {"Reset", "Réinitialiser"},
                {"Total Revenue", "Revenu total"},
                {"Total Payments", "Paiements totaux"},
                {"Average Payment", "Paiement moyen"},
                {"Monthly Revenue", "Revenu mensuel"},
                {"Series 1", "Série 1"},
                {"All", "tout" },
                {"Member Check In / Out", "Entrée/Sortie des membres"},
                {"Search Member:", "Rechercher un membre :"},
          
                {"Currently in Gym:", "Actuellement dans la salle :"},
                {"Today's Attendance Log:", "Journal de présence d’aujourd’hui :"},
                {"Position", "Poste"},
                {"Role", "Rôle"},
                {"Salary", "Salaire"},
                {"Specialization", "Spécialisation"},
                {"Hourly Rate", "Taux horaire"},
               // {"ID", "ID"},
           
               {"Payment ID", "ID de paiement"},
                {"Member Name", "Nom du membre"},
                {"Amount", "Amount"},
                {"Plan Name", "Nom du plan"},
                {"Payment Date", "Date de paiement"},
                {"Emergency Contact Name", "Nom du contact d’urgence"},
                {"Plan ID", "ID du plan"},
{"Name", "Nom"},
{"Duration Name", "Durée"},
{"price", "prix"},
{"description", "description"},

                {"Currentlry in Gym", "Actuellement dans la salle de sport"},
                {"Emergency Contact Phone", "Téléphone du contact d’urgence"},


            };
    }
}
